### ISSUE TITLE
"Rejected send message" on arch

### ISSUE THREAD

**Issue by elleven11** [pop-os/system76-power#178] opened 2020-08-06 14:54 UTC
**Distribution (run `cat /etc/os-release`):**
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
``` 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
system76-acpi-dkms 1.0.1-1
system76-dkms 1.0.9-1
system76-driver 20.04.11-1
system76-firmware-daemon 1.0.13-1
system76-io-dkms 1.0.1-1
system76-power 1.1.6-1
```
Installed from the AUR

**Issue/Bug Description:**
When i run ```system76-power graphics``` i get prompt with this error:
```
daemon returned an error message: "Rejected send message, 1 matched rules; type=\"method_call\", sender=\":1.1554\" (uid=1000 pid=13124 comm=\"system76-power graphics \") interface=\"com.system76.PowerDaemon\" member=\"GetGraphics\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.system76.PowerDaemon\" (uid=0 pid=676 comm=\"/usr/bin/system76-power daemon \")"
```
and if i try to set a graphics mode:
```
setting graphics to nvidia
daemon returned an error message: "Rejected send message, 1 matched rules; type=\"method_call\", sender=\":1.1601\" (uid=1000 pid=13304 comm=\"system76-power graphics nvidia \") interface=\"com.system76.PowerDaemon\" member=\"SetGraphics\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.system76.PowerDaemon\" (uid=0 pid=676 comm=\"/usr/bin/system76-power daemon \")"
```
the logs when the deamon starts:
```
[INFO] Starting daemon
[INFO] Connecting to dbus system bus
[INFO] Rescanning PCI bus
[INFO] 0000:01:00.0: NVIDIA graphics
[INFO] 0000:01:00.2: Function for 0000:01:00.0
[INFO] 0000:01:00.0: Function for 0000:01:00.0
[INFO] 0000:01:00.3: Function for 0000:01:00.0
[INFO] 0000:01:00.1: Function for 0000:01:00.0
[INFO] 0000:00:02.0: Intel graphics
[INFO] 0000:00:02.0: Function for 0000:00:02.0
[INFO] Disabling NMI Watchdog (for kernel debugging only)
[INFO] Setting automatic graphics power
[INFO] Enabling graphics power
[INFO] Initializing with the balanced profile
[INFO] Registering dbus name com.system76.PowerDaemon
[INFO] Adding dbus path /com/system76/PowerDaemon with interface com.system76.PowerDaemon
[ERROR] fan daemon: platform hwmon not found
 [INFO] Handling dbus requests
```
and the deamon does not throw errors when i send it commands.

**Comment by leviport** [comment] 2020-08-06 14:56
Duplicate of https://github.com/pop-os/system76-power/issues/170

I'll reopen it

**Closed by leviport** 2020-08-06 14:56 UTC
