### ISSUE TITLE
Booting up laptop with the lid closed has inconsistent behaviour

### ISSUE THREAD

**Issue by JamesYeoman** [pop-os/system76-power#239] opened 2021-04-20 10:19 UTC
### Distribution (run `cat /etc/os-release`):
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
 
### Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):
```
system76-power:
  Installed: 1.1.16~1618506466~20.04~214e1c8
  Candidate: 1.1.16~1618506466~20.04~214e1c8
  Version table:
 *** 1.1.16~1618506466~20.04~214e1c8 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

### Issue/Bug Description:
When I press the power button, I have to open the laptop lid. When I then close it back up, CryptSetup correctly displays on the monitor, but then when reaching the login screen, the system goes to sleep. I then have to open the lid, and keep it open until I reach the desktop, at which point, the clamshell behaviour kicks in again.

### Steps to reproduce (if you know):
Firstly, make sure to disable "Suspend when laptop lid is closed" in gnome-tweaks.

Then power off, and power on, and make sure the laptop lid is closed.

1. Enter cryptsetup credentials (if applicable)
2. Wait 5-10 seconds (if you have a boot SSD. If you use a boot HDD, then I don't know what the rough timings would be for going from Cryptsetup to Login Screen) to make sure the login screen has a chance to appear
3. Open laptop lid (and witness the laptop being in suspended mode)
4. Press the power button to wake the laptop up from suspend mode
5. Log in
6. When the desktop displays, close the laptop lid
7. Witness the external display continue to be operating

### Expected behavior:
Stock Ubuntu doesn't have this bug. Maybe there's a change that was missed that enabled this Clamshell-on-the-login-screen behaviour

### Other Notes:
If you don't know what I'm referring to when I say clamshell, basically, it's a term coined by Apple that refers to the ability to use solely external peripherals when using a laptop (keyboard, mouse, and monitor) and having the laptop lid closed. It's particularly useful in restricted spaces where you want the larger monitor but can't afford enough room for the laptop to also be open constantly.

It's also worth noting that upon reaching the desktop, if you then lock the system, the clamshell still works and you can login without opening the laptop up. It's just the initial login that needs it to be open

**Comment by leviport** [comment] 2021-04-20 14:54
Duplicate of https://github.com/pop-os/pop/issues/1655

**Closed by leviport** 2021-04-20 14:54 UTC
