### ISSUE TITLE
[Request] Disable Gnome animations on "Battery Life" mode

### ISSUE THREAD

**Issue by juxuanu** [pop-os/system76-power#192] opened 2020-09-25 09:02 UTC
On my laptop I have better battery life when the Gnome animations are disabled. I think it'd be nice if the animations were disabled on "Battery Life" mode and then enabled again on any of the other modes. 
Basically, `gsettings set org.gnome.desktop.interface enable-animations false` or `true` accordingly.

**Comment by kylebakerio** [comment] 2021-02-27 14:29
Do you have data on how significant the effect is?

**Comment by crawfxrd** [comment] 2021-11-24 15:24
Duplicate of #108.

**Closed by crawfxrd** 2021-11-24 15:24 UTC
